export enum CONNECTION_STATUS {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  EXPIRED = 'EXPIRED',
}

export const RATE_LIMITS = {
  DAILY_LIMIT: 500,
  MESSAGES_PER_MINUTE: 10,
}

export const QR_EXPIRY_SECONDS = 180 // 3 minutes
